# Generated by Django 4.1 on 2022-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0009_alter_submission_abstract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="authentication",
            field=models.FileField(upload_to="doc/"),
        ),
    ]
