# Generated by Django 4.1 on 2022-11-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0010_alter_submission_authentication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission", old_name="co1", new_name="address",
        ),
        migrations.RenameField(
            model_name="submission", old_name="co2", new_name="branch",
        ),
        migrations.RenameField(
            model_name="submission", old_name="field", new_name="mail",
        ),
        migrations.RenameField(
            model_name="submission", old_name="author", new_name="name",
        ),
        migrations.RenameField(
            model_name="submission", old_name="mail2", new_name="program",
        ),
        migrations.RenameField(
            model_name="submission", old_name="mail1", new_name="roll_no",
        ),
        migrations.RenameField(
            model_name="submission", old_name="co3", new_name="year",
        ),
        migrations.RemoveField(model_name="submission", name="abstract",),
        migrations.RemoveField(model_name="submission", name="authentication",),
        migrations.RemoveField(model_name="submission", name="degree",),
        migrations.RemoveField(model_name="submission", name="mail3",),
        migrations.RemoveField(model_name="submission", name="others",),
        migrations.RemoveField(model_name="submission", name="title",),
    ]
