# Generated by Django 4.1 on 2022-12-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0011_rename_co1_submission_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="mail",),
    ]
